/**
 * Static, Metro-bundlable map of UI sound effects.
 *
 * REGENERATED BY: `pnpm --filter @workspace/catfish run sfx:pregen`
 *
 * Why static `require()` instead of dynamic file lookup:
 *   Metro needs to see literal `require("./...wav")` strings at build
 *   time so it knows to copy each asset into the bundle. A dynamic
 *   `require(string)` breaks both web and native builds.
 *
 * Each entry maps a stable `SfxName` to a bundled asset reference
 * (a number on native, an object on web — both shapes are accepted
 * by expo-audio's `useAudioPlayer`).
 */

export type SfxName =
  | "swipe_pass"
  | "swipe_like"
  | "match"
  | "fact_filed"
  | "day_end"
  | "accuse"
  | "win"
  | "lose";

const SFX_MANIFEST: Record<SfxName, number | object> = {
  swipe_pass: require("@/assets/audio/sfx/swipe_pass.wav"),
  swipe_like: require("@/assets/audio/sfx/swipe_like.wav"),
  match: require("@/assets/audio/sfx/match.wav"),
  fact_filed: require("@/assets/audio/sfx/fact_filed.wav"),
  day_end: require("@/assets/audio/sfx/day_end.wav"),
  accuse: require("@/assets/audio/sfx/accuse.wav"),
  win: require("@/assets/audio/sfx/win.wav"),
  lose: require("@/assets/audio/sfx/lose.wav"),
};

export function sfxAsset(name: SfxName): number | object {
  return SFX_MANIFEST[name];
}

export const MUSIC_LOOP_ASSET: number | object = require("@/assets/audio/music/noir_loop.wav");
