/**
 * Innocent dialogue tree pool — 30 distinct 4-turn chat trees that
 * non-killer matches draw from at thread-open time. Each thread in a
 * given run claims a unique tree id (see `CaseRun.usedInnocentScriptIds`)
 * so two innocent matches in the same run never deliver the same
 * scripted opener.
 *
 * Generated by `scripts/generate-innocent-trees.mts`. Hand-edits
 * are welcome — the generator is a one-shot bootstrap, not a
 * deploy-time step. If you re-run the generator, review the diff
 * carefully before committing.
 *
 * Trees are sorted by id so the file diff is deterministic across
 * regenerations.
 */
import type { DialogueTurn } from "./identities";

export interface InnocentTree {
  /** Stable kebab-case id; doubles as the AsyncStorage check-out key. */
  id: string;
  /** Author-facing one-liner (not surfaced in UI). */
  personaConcept: string;
  /** Always 4 turns today. */
  turns: DialogueTurn[];
}

export const INNOCENT_TREE_POOL: readonly InnocentTree[] = [
  {
    id: "astronomer",
    personaConcept: "A dreamy astronomer who sees the universe in a grain of sand.",
    turns: [
      {
        beatKey: "astronomer__open",
        suspectMessages: [
          "hi. do you ever just look up at the sky and feel small?",
        ],
        replyOptions: [
          "all the time. it's humbling.",
          "not as small as i feel doing my taxes.",
          "is this an astrology question?",
        ],
      },
      {
        beatKey: "astronomer__warmup",
        suspectMessages: [
          "ha, definitely not astrology. more... cosmic perspective.",
          "are you an indoor or an outdoor person?",
        ],
        replyOptions: [
          "outdoors, for sure.",
          "indoors. there's wifi here.",
          "depends on the weather.",
        ],
      },
      {
        beatKey: "astronomer__reveal",
        suspectMessages: [
          "i spend a lot of time indoors looking at the outdoors.",
          "if that makes any sense. i work at the planetarium.",
        ],
        replyOptions: [
          "that makes perfect sense.",
          "so you get the best of both worlds.",
          "what do you do there?",
        ],
      },
      {
        beatKey: "astronomer__close",
        suspectMessages: [
          "i mostly map stellar nurseries. it's pretty quiet.",
          "i could give you a private tour of the stars sometime.",
        ],
        replyOptions: [
          "wow, i would love that.",
          "will you name a star after me?",
          "is that your job?",
        ],
      },
    ],
  },
  {
    id: "bike-mechanic",
    personaConcept: "A practical vintage bike mechanic who's more comfortable with gears than with small talk.",
    turns: [
      {
        beatKey: "bike-mechanic__open",
        suspectMessages: [
          "hey. nice bike in your third picture.",
        ],
        replyOptions: [
          "thanks, i love that bike.",
          "you noticed the bike, huh?",
          "are you a cyclist?",
        ],
      },
      {
        beatKey: "bike-mechanic__warmup",
        suspectMessages: [
          "yeah, it's a classic frame. good choice.",
          "do you do your own repairs?",
        ],
        replyOptions: [
          "only the simple stuff.",
          "i pay a professional to get greasy.",
          "should i?",
        ],
      },
      {
        beatKey: "bike-mechanic__reveal",
        suspectMessages: [
          "depends. i happen to like getting my hands dirty.",
          "i'm usually fixing up old steel frames in my shop.",
        ],
        replyOptions: [
          "that's really cool.",
          "a person of many talents.",
          "you have a shop?",
        ],
      },
      {
        beatKey: "bike-mechanic__close",
        suspectMessages: [
          "it's more of a garage, but yeah.",
          "if you ever need a tune-up, you should swing by.",
        ],
        replyOptions: [
          "i'll keep that in mind, thanks.",
          "is that your version of asking me out?",
          "what kind of bikes do you fix?",
        ],
      },
    ],
  },
  {
    id: "cellist",
    personaConcept: "An elegant and disciplined cellist who's more comfortable expressing herself through music.",
    turns: [
      {
        beatKey: "cellist__open",
        suspectMessages: [
          "hello. there's a certain grace to your photos.",
        ],
        replyOptions: [
          "thank you, that's very kind.",
          "i'm actually incredibly clumsy.",
          "what do you mean by grace?",
        ],
      },
      {
        beatKey: "cellist__warmup",
        suspectMessages: [
          "it's just a feeling. a certain composure.",
          "what kind of music do you listen to when you want to focus?",
        ],
        replyOptions: [
          "classical music, usually.",
          "very loud heavy metal.",
          "i need total silence.",
        ],
      },
      {
        beatKey: "cellist__reveal",
        suspectMessages: [
          "i understand all three of those, actually.",
          "i spend most of my days with a cello between my knees.",
        ],
        replyOptions: [
          "you're a musician?",
          "that sounds very elegant.",
          "is it heavy?",
        ],
      },
      {
        beatKey: "cellist__close",
        suspectMessages: [
          "i play in a string quartet. it requires a lot of practice.",
          "we have a concert coming up, if you'd like to listen.",
        ],
        replyOptions: [
          "i would love that.",
          "do i have to dress up?",
          "what are you playing?",
        ],
      },
    ],
  },
  {
    id: "ceramicist-dawn",
    personaConcept: "An early-rising artist who finds peace at the potter's wheel before the sun is up.",
    turns: [
      {
        beatKey: "ceramicist-dawn__open",
        suspectMessages: [
          "hey, your profile has a nice quiet feel to it.",
        ],
        replyOptions: [
          "thanks, i like quiet.",
          "are you saying i'm boring?",
          "what does quiet feel like?",
        ],
      },
      {
        beatKey: "ceramicist-dawn__warmup",
        suspectMessages: [
          "ha, not at all. just calm.",
          "are you more of a morning person or a night owl?",
        ],
        replyOptions: [
          "definitely a morning person.",
          "i'm an 'after coffee' person.",
          "depends on the day. and you?",
        ],
      },
      {
        beatKey: "ceramicist-dawn__reveal",
        suspectMessages: [
          "i'm usually up before the sun is.",
          "that's when the clay is best anyway.",
        ],
        replyOptions: [
          "that sounds so peaceful.",
          "so that's your secret.",
          "what happens with the clay?",
        ],
      },
      {
        beatKey: "ceramicist-dawn__close",
        suspectMessages: [
          "it's my favorite part of the day.",
          "maybe i could show you some of my work sometime.",
        ],
        replyOptions: [
          "i would love that.",
          "only if i get to try the wheel.",
          "what kind of work is it?",
        ],
      },
    ],
  },
  {
    id: "chem-teacher",
    personaConcept: "A slightly nerdy high-school chemistry teacher who sees the world as a series of reactions.",
    turns: [
      {
        beatKey: "chem-teacher__open",
        suspectMessages: [
          "hi. i feel like we might have good chemistry.",
        ],
        replyOptions: [
          "that's a very smooth line.",
          "was that a science pun?",
          "what makes you say that?",
        ],
      },
      {
        beatKey: "chem-teacher__warmup",
        suspectMessages: [
          "sorry, occupational hazard.",
          "what was your favorite subject in school?",
        ],
        replyOptions: [
          "i was always an english person.",
          "lunch, without a doubt.",
          "definitely not chemistry.",
        ],
      },
      {
        beatKey: "chem-teacher__reveal",
        suspectMessages: [
          "ah, a shame. i find it fascinating.",
          "i try to convince teenagers of that every day.",
        ],
        replyOptions: [
          "you're a teacher?",
          "that sounds like a noble, but difficult, cause.",
          "how do you do that?",
        ],
      },
      {
        beatKey: "chem-teacher__close",
        suspectMessages: [
          "mostly by blowing things up. safely, of course.",
          "maybe i could show you a cool experiment sometime.",
        ],
        replyOptions: [
          "i'd love to see that.",
          "as long as i don't have to do homework.",
          "what kind of experiment?",
        ],
      },
    ],
  },
  {
    id: "choir-director",
    personaConcept: "A warm and encouraging choir director who finds harmony in everyday life.",
    turns: [
      {
        beatKey: "choir-director__open",
        suspectMessages: [
          "hello. you have a very kind and harmonious aura.",
        ],
        replyOptions: [
          "what a nice thing to say, thank you.",
          "are you sure that's not just feedback?",
          "harmonious? i like that.",
        ],
      },
      {
        beatKey: "choir-director__warmup",
        suspectMessages: [
          "it's a good quality to have.",
          "are you much of a singer? shower-singers count.",
        ],
        replyOptions: [
          "i sing in the car sometimes.",
          "i'm completely tone-deaf, sadly.",
          "what about you?",
        ],
      },
      {
        beatKey: "choir-director__reveal",
        suspectMessages: [
          "ha, i sing a little. i direct a small church choir.",
          "it's my job to get everyone to sing together.",
        ],
        replyOptions: [
          "that sounds like a beautiful job.",
          "so you're a professional herder of cats.",
          "is it hard to do?",
        ],
      },
      {
        beatKey: "choir-director__close",
        suspectMessages: [
          "it can be tricky, but it's wonderful when it works.",
          "we have a rehearsal that's open to visitors, if you're ever curious.",
        ],
        replyOptions: [
          "i'd really enjoy that.",
          "will you make me sing?",
          "what kind of music do you do?",
        ],
      },
    ],
  },
  {
    id: "city-archivist",
    personaConcept: "A quiet and detail-oriented city archivist who loves uncovering old stories.",
    turns: [
      {
        beatKey: "city-archivist__open",
        suspectMessages: [
          "hello. i get the feeling you have a good story.",
        ],
        replyOptions: [
          "thank you. i have a few.",
          "it's a long and boring story.",
          "what makes you think that?",
        ],
      },
      {
        beatKey: "city-archivist__warmup",
        suspectMessages: [
          "everyone does. you just have to know what to look for.",
          "are you from this city originally?",
        ],
        replyOptions: [
          "yes, born and raised.",
          "no, i moved here a few years ago.",
          "does anyone ever say yes to that?",
        ],
      },
      {
        beatKey: "city-archivist__reveal",
        suspectMessages: [
          "i ask because i spend my days digging through the city's past.",
          "i'm an archivist down at the main library.",
        ],
        replyOptions: [
          "that must be such an interesting job.",
          "so you read other people's mail for a living.",
          "what kind of things do you find?",
        ],
      },
      {
        beatKey: "city-archivist__close",
        suspectMessages: [
          "mostly old maps and letters. forgotten things.",
          "sometime i could show you the oldest photo we have of your street.",
        ],
        replyOptions: [
          "i would be fascinated to see that.",
          "only if you can find some old gossip.",
          "you can look that up?",
        ],
      },
    ],
  },
  {
    id: "dog-trainer",
    personaConcept: "A confident and direct dog trainer who probably likes your dog more than you.",
    turns: [
      {
        beatKey: "dog-trainer__open",
        suspectMessages: [
          "is that your dog in your pictures?",
          "looks like a good boy.",
        ],
        replyOptions: [
          "he's the best boy.",
          "he's a menace but i love him.",
          "can you tell his breed from the photo?",
        ],
      },
      {
        beatKey: "dog-trainer__warmup",
        suspectMessages: [
          "looks like some kind of shepherd mix maybe?",
          "what's the smartest trick you've taught him?",
        ],
        replyOptions: [
          "he can shake hands.",
          "he taught me how to give him treats.",
          "he's not much for tricks.",
        ],
      },
      {
        beatKey: "dog-trainer__reveal",
        suspectMessages: [
          "ha, the smart ones always train their owners.",
          "i spend most of my days with big goofy dogs like him.",
        ],
        replyOptions: [
          "that sounds like the best job.",
          "so you're a professional dog-petter?",
          "are you a trainer?",
        ],
      },
      {
        beatKey: "dog-trainer__close",
        suspectMessages: [
          "something like that. it's mostly about training the people.",
          "we should take our dogs to the park sometime.",
        ],
        replyOptions: [
          "he would love that.",
          "a doggy date? i'm in.",
          "do you have a dog too?",
        ],
      },
    ],
  },
  {
    id: "er-nurse",
    personaConcept: "An exhausted but compassionate ER nurse who's just gotten off a long shift.",
    turns: [
      {
        beatKey: "er-nurse__open",
        suspectMessages: [
          "just got off a twelve hour shift.",
          "your profile is much calmer than my night has been.",
        ],
        replyOptions: [
          "i hope you can get some rest.",
          "i'm pretty calm, it's true.",
          "rough night?",
        ],
      },
      {
        beatKey: "er-nurse__warmup",
        suspectMessages: [
          "rest is a distant dream. coffee is my reality.",
          "what's the most relaxing thing you can think of right now?",
        ],
        replyOptions: [
          "reading a book in total silence.",
          "not talking to anyone for a full day.",
          "you should try to get some sleep.",
        ],
      },
      {
        beatKey: "er-nurse__reveal",
        suspectMessages: [
          "silence sounds like a miracle.",
          "the er is anything but quiet, especially on a full moon.",
        ],
        replyOptions: [
          "you work in the er? wow.",
          "i can't even imagine.",
          "is the full moon thing real?",
        ],
      },
      {
        beatKey: "er-nurse__close",
        suspectMessages: [
          "it is absolutely real. don't let anyone tell you otherwise.",
          "maybe when i'm less tired we could get that coffee.",
        ],
        replyOptions: [
          "i would like that very much.",
          "you'd better get some rest first.",
          "deal. when are you free?",
        ],
      },
    ],
  },
  {
    id: "ferry-captain",
    personaConcept: "A steady and reliable ferry captain who knows the water better than the land.",
    turns: [
      {
        beatKey: "ferry-captain__open",
        suspectMessages: [
          "your profile seems very down to earth.",
        ],
        replyOptions: [
          "thanks, i try to be.",
          "as opposed to what, up in the clouds?",
          "and yours seems very... watery.",
        ],
      },
      {
        beatKey: "ferry-captain__warmup",
        suspectMessages: [
          "that's a fair assessment. i am on the water a lot.",
          "do you get seasick?",
        ],
        replyOptions: [
          "not usually, no.",
          "only on tuesdays.",
          "is that a dealbreaker?",
        ],
      },
      {
        beatKey: "ferry-captain__reveal",
        suspectMessages: [
          "ha, not a dealbreaker. just a practical question.",
          "i drive the ten o'clock ferry on the inland route.",
        ],
        replyOptions: [
          "wow, you're a captain.",
          "you drive a boat? that's so cool.",
          "is it a hard job?",
        ],
      },
      {
        beatKey: "ferry-captain__close",
        suspectMessages: [
          "it's steady. you see some amazing sunrises.",
          "i could take you for a ride on my route sometime.",
        ],
        replyOptions: [
          "i would love that.",
          "do i get to steer?",
          "is that allowed?",
        ],
      },
    ],
  },
  {
    id: "florist-no-roses",
    personaConcept: "An opinionated florist with a passion for unusual blooms and a distaste for clichés.",
    turns: [
      {
        beatKey: "florist-no-roses__open",
        suspectMessages: [
          "i'm going to guess your favorite flower is not a red rose.",
        ],
        replyOptions: [
          "you would be correct.",
          "what, are they not good enough for you?",
          "how could you tell?",
        ],
      },
      {
        beatKey: "florist-no-roses__warmup",
        suspectMessages: [
          "they're just so boring. so expected.",
          "what's a flower you actually like?",
        ],
        replyOptions: [
          "i love peonies.",
          "dandelions. they're resilient.",
          "what do you recommend?",
        ],
      },
      {
        beatKey: "florist-no-roses__reveal",
        suspectMessages: [
          "good choice. i'm more of a thistle and protea person myself.",
          "i run a flower shop that has a strict no-rose policy.",
        ],
        replyOptions: [
          "that's a bold business move.",
          "a flower rebel. i love it.",
          "why no roses?",
        ],
      },
      {
        beatKey: "florist-no-roses__close",
        suspectMessages: [
          "there are so many more interesting flowers out there.",
          "you should come by the shop. i'll make you a bouquet.",
        ],
        replyOptions: [
          "that's a lovely offer.",
          "as long as it has no roses.",
          "what's your shop called?",
        ],
      },
    ],
  },
  {
    id: "game-designer",
    personaConcept: "A thoughtful indie game designer who thinks about the world in terms of systems and fun.",
    turns: [
      {
        beatKey: "game-designer__open",
        suspectMessages: [
          "hi. if your life was a video game, what genre would it be?",
        ],
        replyOptions: [
          "probably a cozy life simulator.",
          "a chaotic sandbox game.",
          "that's a new one. what about you?",
        ],
      },
      {
        beatKey: "game-designer__warmup",
        suspectMessages: [
          "mine is a puzzle game with a very confusing tutorial.",
          "what's a game you've sunk way too much time into?",
        ],
        replyOptions: [
          "stardew valley, for sure.",
          "the game of life. my score is not great.",
          "i don't play a lot of games.",
        ],
      },
      {
        beatKey: "game-designer__reveal",
        suspectMessages: [
          "that's fair. i guess i play them for a living.",
          "i'm designing a little indie game right now.",
        ],
        replyOptions: [
          "that's my dream job.",
          "so you're saying you need a beta tester?",
          "what's it about?",
        ],
      },
      {
        beatKey: "game-designer__close",
        suspectMessages: [
          "it's mostly about a little ghost who delivers mail.",
          "maybe i could show you the prototype sometime.",
        ],
        replyOptions: [
          "that sounds adorable, i'd love to.",
          "i'd be happy to break it for you.",
          "is it fun?",
        ],
      },
    ],
  },
  {
    id: "ice-climber",
    personaConcept: "An adventurous and focused ice climber who guides on weekends.",
    turns: [
      {
        beatKey: "ice-climber__open",
        suspectMessages: [
          "your profile looks adventurous. i like that.",
        ],
        replyOptions: [
          "thanks, i try to get out there.",
          "i'm pretty adventurous in the snack aisle.",
          "what do you consider adventurous?",
        ],
      },
      {
        beatKey: "ice-climber__warmup",
        suspectMessages: [
          "anything that gets your heart rate up a little.",
          "so what's your relationship with heights?",
        ],
        replyOptions: [
          "i don't mind them.",
          "we have a restraining order against each other.",
          "are you about to ask me to go climbing?",
        ],
      },
      {
        beatKey: "ice-climber__reveal",
        suspectMessages: [
          "ha, not rock climbing. ice climbing.",
          "i spend my winter weekends on frozen waterfalls.",
        ],
        replyOptions: [
          "that sounds both terrifying and amazing.",
          "you climb frozen water? why?",
          "is that safe?",
        ],
      },
      {
        beatKey: "ice-climber__close",
        suspectMessages: [
          "it's safer than it sounds. very calm, very focused.",
          "maybe we could go for a simple hike sometime first.",
        ],
        replyOptions: [
          "a hike sounds perfect.",
          "as long as it's not a vertical hike.",
          "where do you like to go?",
        ],
      },
    ],
  },
  {
    id: "lighting-designer",
    personaConcept: "A moody, artistic lighting designer who sees the world in terms of light and shadow.",
    turns: [
      {
        beatKey: "lighting-designer__open",
        suspectMessages: [
          "the lighting in your first photo is really good.",
        ],
        replyOptions: [
          "oh, thanks. it was a lucky shot.",
          "are you a photographer?",
          "you noticed the lighting?",
        ],
      },
      {
        beatKey: "lighting-designer__warmup",
        suspectMessages: [
          "i always notice the lighting. it's a professional habit.",
          "are you more of a sunrise person or a sunset person?",
        ],
        replyOptions: [
          "definitely sunset.",
          "i'm more of a 'fluorescent hum at 2am' person.",
          "what's the difference?",
        ],
      },
      {
        beatKey: "lighting-designer__reveal",
        suspectMessages: [
          "the color temperature is completely different.",
          "i design the lights for plays. i paint with it.",
        ],
        replyOptions: [
          "that must be an amazing job.",
          "so you're the person who makes actors look good.",
          "how do you 'paint with light'?",
        ],
      },
      {
        beatKey: "lighting-designer__close",
        suspectMessages: [
          "it's all about mood and shadow. telling a story.",
          "i'm teching a show, you could come see my work in action.",
        ],
        replyOptions: [
          "i'd love to see that.",
          "can you make me look good with lighting?",
          "what's the play?",
        ],
      },
    ],
  },
  {
    id: "moss-botanist",
    personaConcept: "A patient botanist who studies the tiny, overlooked world of coastal moss.",
    turns: [
      {
        beatKey: "moss-botanist__open",
        suspectMessages: [
          "hello. i like that you seem to notice the small things.",
        ],
        replyOptions: [
          "i try to. thanks for noticing.",
          "are you calling me short?",
          "what made you say that?",
        ],
      },
      {
        beatKey: "moss-botanist__warmup",
        suspectMessages: [
          "it's in the details of your photos.",
          "what's your favorite season and why?",
        ],
        replyOptions: [
          "autumn. for the colors and the cool air.",
          "spring. everything feels new.",
          "the rainy season.",
        ],
      },
      {
        beatKey: "moss-botanist__reveal",
        suspectMessages: [
          "i love the rainy season. it's good for my work.",
          "i study the different kinds of moss along the coast.",
        ],
        replyOptions: [
          "that sounds incredibly peaceful.",
          "moss? really? what's to study?",
          "you're a botanist?",
        ],
      },
      {
        beatKey: "moss-botanist__close",
        suspectMessages: [
          "it's a whole tiny world once you look close enough.",
          "we could go for a walk by the shore sometime, i'll show you.",
        ],
        replyOptions: [
          "i would love that.",
          "will there be a quiz?",
          "where's the best place to go?",
        ],
      },
    ],
  },
  {
    id: "mystery-bookseller",
    personaConcept: "A cozy bookstore manager who has a special love for a good mystery.",
    turns: [
      {
        beatKey: "mystery-bookseller__open",
        suspectMessages: [
          "i have a feeling you're a bit of a mystery.",
        ],
        replyOptions: [
          "i like to keep a little mystery.",
          "i'm an open book, actually.",
          "what gives you that impression?",
        ],
      },
      {
        beatKey: "mystery-bookseller__warmup",
        suspectMessages: [
          "everyone has a few secrets. it makes things interesting.",
          "what's the last book you read?",
        ],
        replyOptions: [
          "a really good thriller.",
          "i mostly read articles online.",
          "i can't remember.",
        ],
      },
      {
        beatKey: "mystery-bookseller__reveal",
        suspectMessages: [
          "i love a good thriller. it's my favorite section.",
          "i manage a little bookstore downtown.",
        ],
        replyOptions: [
          "oh, i love bookstores.",
          "so you get to read all day?",
          "which one?",
        ],
      },
      {
        beatKey: "mystery-bookseller__close",
        suspectMessages: [
          "less reading than you'd think. mostly unpacking boxes.",
          "you should come by. i can give you a recommendation.",
        ],
        replyOptions: [
          "i would love a recommendation.",
          "only if it's a really good mystery.",
          "are you there now?",
        ],
      },
    ],
  },
  {
    id: "neighborhood-mechanic",
    personaConcept: "A trustworthy, down-to-earth mechanic who can fix just about anything with wheels.",
    turns: [
      {
        beatKey: "neighborhood-mechanic__open",
        suspectMessages: [
          "hey. you seem like a reliable person.",
        ],
        replyOptions: [
          "thanks, i'd like to think so.",
          "i have my moments of chaos.",
          "as opposed to what?",
        ],
      },
      {
        beatKey: "neighborhood-mechanic__warmup",
        suspectMessages: [
          "ha, fair enough. a little chaos is good.",
          "what's the first car you ever owned?",
        ],
        replyOptions: [
          "a beat-up old honda civic.",
          "i still don't own a car.",
          "why do you ask?",
        ],
      },
      {
        beatKey: "neighborhood-mechanic__reveal",
        suspectMessages: [
          "just curious. i like hearing about people's cars.",
          "i'm the guy everyone in the neighborhood calls when they break down.",
        ],
        replyOptions: [
          "so you're a mechanic.",
          "a neighborhood hero!",
          "do you enjoy that?",
        ],
      },
      {
        beatKey: "neighborhood-mechanic__close",
        suspectMessages: [
          "i like fixing things that are broken. it's satisfying.",
          "if you ever have car trouble, we should talk.",
        ],
        replyOptions: [
          "i'll definitely keep you in mind.",
          "is this your way of offering me a free oil change?",
          "can you teach me how to fix my car?",
        ],
      },
    ],
  },
  {
    id: "noodle-critic",
    personaConcept: "A food critic with very strong and specific opinions about noodles.",
    turns: [
      {
        beatKey: "noodle-critic__open",
        suspectMessages: [
          "i need to know your stance on ramen immediately.",
        ],
        replyOptions: [
          "i'm very pro-ramen.",
          "depends, who's asking?",
          "is this a trick question?",
        ],
      },
      {
        beatKey: "noodle-critic__warmup",
        suspectMessages: [
          "good. we can proceed.",
          "what's more important: the broth or the noodles?",
        ],
        replyOptions: [
          "definitely the broth.",
          "the noodles, obviously.",
          "the little swirly fish cake.",
        ],
      },
      {
        beatKey: "noodle-critic__reveal",
        suspectMessages: [
          "wrong. it's the chew of the noodle. always.",
          "i have very strong opinions on this, as you can tell.",
        ],
        replyOptions: [
          "i can see that.",
          "are you a professional noodle-eater?",
          "what gives you the authority?",
        ],
      },
      {
        beatKey: "noodle-critic__close",
        suspectMessages: [
          "you could say that. i write about food for a living.",
          "i'm on a quest for the city's best noodles. care to join?",
        ],
        replyOptions: [
          "yes, absolutely.",
          "i will be your noodle-eating sidekick.",
          "where should we go first?",
        ],
      },
    ],
  },
  {
    id: "open-mic-comic",
    personaConcept: "A self-deprecating stand-up comic who's always looking for new material.",
    turns: [
      {
        beatKey: "open-mic-comic__open",
        suspectMessages: [
          "hey. on a scale of one to ten, how funny is your profile?",
        ],
        replyOptions: [
          "i'd give it a solid seven.",
          "is this a test?",
          "i don't know, you tell me.",
        ],
      },
      {
        beatKey: "open-mic-comic__warmup",
        suspectMessages: [
          "i'm just workshopping some new material. you're a tough crowd.",
          "what's the most embarrassing thing you've done this week?",
        ],
        replyOptions: [
          "waved back at someone who wasn't waving at me.",
          "i'm not telling you. you'll use it in your act.",
          "is this for your diary?",
        ],
      },
      {
        beatKey: "open-mic-comic__reveal",
        suspectMessages: [
          "ha, you caught me. i'm always looking for inspiration.",
          "i do stand-up at open mics. it's mostly just embarrassing.",
        ],
        replyOptions: [
          "that's really brave.",
          "so you get paid in embarrassment?",
          "how's it been going?",
        ],
      },
      {
        beatKey: "open-mic-comic__close",
        suspectMessages: [
          "last night a guy heckled me by just yawning loudly.",
          "you should come watch me bomb sometime. for moral support.",
        ],
        replyOptions: [
          "i'd be happy to.",
          "i'll be your one pity laugh.",
          "where do you perform?",
        ],
      },
    ],
  },
  {
    id: "overnight-dj",
    personaConcept: "A chill, somewhat solitary radio DJ who keeps the city company after midnight.",
    turns: [
      {
        beatKey: "overnight-dj__open",
        suspectMessages: [
          "hey. are you up late often?",
        ],
        replyOptions: [
          "pretty often, yeah.",
          "only when i'm procrastinating.",
          "is this a booty call?",
        ],
      },
      {
        beatKey: "overnight-dj__warmup",
        suspectMessages: [
          "ha, no. just making conversation.",
          "what's the last song you listened to on purpose?",
        ],
        replyOptions: [
          "something by a band you've never heard of.",
          "probably the theme song to a tv show.",
          "you first.",
        ],
      },
      {
        beatKey: "overnight-dj__reveal",
        suspectMessages: [
          "i listen to a lot of songs on purpose. it's my job.",
          "i'm on the radio from midnight to six.",
        ],
        replyOptions: [
          "no way, that's so cool.",
          "you have the perfect voice for radio.",
          "what station?",
        ],
      },
      {
        beatKey: "overnight-dj__close",
        suspectMessages: [
          "it's quiet work. just me and the music.",
          "maybe we could get a coffee sometime during daylight hours.",
        ],
        replyOptions: [
          "i'd love that.",
          "only if you dedicate a song to me.",
          "when do you sleep?",
        ],
      },
    ],
  },
  {
    id: "paramedic-dry",
    personaConcept: "A paramedic with a bone-dry sense of humor, catching a break between long shifts.",
    turns: [
      {
        beatKey: "paramedic-dry__open",
        suspectMessages: [
          "your profile seems significantly less chaotic than my job.",
        ],
        replyOptions: [
          "is that a good thing?",
          "and here i was trying to be chaotic.",
          "what's your job?",
        ],
      },
      {
        beatKey: "paramedic-dry__warmup",
        suspectMessages: [
          "it's a very good thing. trust me.",
          "so what's your go-to method for de-stressing?",
        ],
        replyOptions: [
          "a long walk, usually.",
          "scrolling on my phone for three hours.",
          "why, you need a new one?",
        ],
      },
      {
        beatKey: "paramedic-dry__reveal",
        suspectMessages: [
          "i probably do. my shifts have been a little wild.",
          "let's just say i see some interesting things.",
        ],
        replyOptions: [
          "i'm sorry to hear that.",
          "at least you have good stories.",
          "interesting how?",
        ],
      },
      {
        beatKey: "paramedic-dry__close",
        suspectMessages: [
          "oh, they're not good stories. just weird ones.",
          "maybe i could tell you one over a drink sometime.",
        ],
        replyOptions: [
          "i'd like that a lot.",
          "as long as it's not too gross.",
          "are you free this week?",
        ],
      },
    ],
  },
  {
    id: "perfumer-apprentice",
    personaConcept: "A perfumer's apprentice who experiences the world through scent.",
    turns: [
      {
        beatKey: "perfumer-apprentice__open",
        suspectMessages: [
          "this is a weird question, but what scent do you like most?",
        ],
        replyOptions: [
          "rain on hot pavement.",
          "freshly baked cookies.",
          "why do you ask?",
        ],
      },
      {
        beatKey: "perfumer-apprentice__warmup",
        suspectMessages: [
          "oh, that's a good one. petrichor.",
          "do you wear a signature perfume or cologne?",
        ],
        replyOptions: [
          "i have one i really like.",
          "no, i don't really wear any.",
          "are you a scent expert?",
        ],
      },
      {
        beatKey: "perfumer-apprentice__reveal",
        suspectMessages: [
          "i'm trying to be. i'm a perfumer's apprentice.",
          "i spend my days smelling things like sandalwood and bergamot.",
        ],
        replyOptions: [
          "that sounds like a dream job.",
          "so you smell good all the time?",
          "what are you working on?",
        ],
      },
      {
        beatKey: "perfumer-apprentice__close",
        suspectMessages: [
          "mostly i just smell like 20 things at once.",
          "maybe we could get a coffee. i'd love to know what you think of a new scent.",
        ],
        replyOptions: [
          "i would be honored.",
          "can i be your official smeller?",
          "what does it smell like?",
        ],
      },
    ],
  },
  {
    id: "rec-center-potter",
    personaConcept: "A friendly and encouraging pottery teacher at the local rec center.",
    turns: [
      {
        beatKey: "rec-center-potter__open",
        suspectMessages: [
          "hey there. you seem like a creative person.",
        ],
        replyOptions: [
          "thanks, i like to make things.",
          "my creativity is mostly making up excuses.",
          "what makes you say that?",
        ],
      },
      {
        beatKey: "rec-center-potter__warmup",
        suspectMessages: [
          "it's just a vibe. what's the last thing you made with your hands?",
          "food counts.",
        ],
        replyOptions: [
          "i made a pretty good sandwich.",
          "a mess, probably.",
          "i'm not very crafty.",
        ],
      },
      {
        beatKey: "rec-center-potter__reveal",
        suspectMessages: [
          "that's okay. it's more about the trying than the final product.",
          "i teach a pottery class at the rec center.",
        ],
        replyOptions: [
          "that sounds like so much fun.",
          "is it like that scene in ghost?",
          "are you a good teacher?",
        ],
      },
      {
        beatKey: "rec-center-potter__close",
        suspectMessages: [
          "i'm very patient, which is what matters.",
          "you should drop in for a class sometime. no experience needed.",
        ],
        replyOptions: [
          "i think i'll take you up on that.",
          "i promise to make something ugly.",
          "when are your classes?",
        ],
      },
    ],
  },
  {
    id: "salsa-accountant",
    personaConcept: "A forensic accountant by day who lives a secret, passionate life as a salsa dancer by night.",
    turns: [
      {
        beatKey: "salsa-accountant__open",
        suspectMessages: [
          "your profile looks very... organized.",
        ],
        replyOptions: [
          "thank you, i appreciate order.",
          "it's all a facade, i'm a mess.",
          "is 'organized' a compliment?",
        ],
      },
      {
        beatKey: "salsa-accountant__warmup",
        suspectMessages: [
          "to me, it is. my day job is all about numbers.",
          "so, what do you do to break out of your routine?",
        ],
        replyOptions: [
          "i like to go hiking on weekends.",
          "try a new recipe for dinner.",
          "i don't have a routine.",
        ],
      },
      {
        beatKey: "salsa-accountant__reveal",
        suspectMessages: [
          "i have a very strict routine. but i have a secret.",
          "a few nights a week, i go salsa dancing.",
        ],
        replyOptions: [
          "that's a great secret.",
          "an accountant who salsa dances?",
          "are you any good?",
        ],
      },
      {
        beatKey: "salsa-accountant__close",
        suspectMessages: [
          "i'm pretty good. it's the opposite of spreadsheets.",
          "i could teach you a few steps sometime if you're interested.",
        ],
        replyOptions: [
          "i would love that.",
          "i have two left feet.",
          "where do you go dancing?",
        ],
      },
    ],
  },
  {
    id: "slam-poet",
    personaConcept: "An intense and expressive slam poet who lives for the rhythm of words.",
    turns: [
      {
        beatKey: "slam-poet__open",
        suspectMessages: [
          "your profile has a certain rhythm to it.",
        ],
        replyOptions: [
          "thank you, i think.",
          "is it a good rhythm?",
          "what do you mean by that?",
        ],
      },
      {
        beatKey: "slam-poet__warmup",
        suspectMessages: [
          "like a steady beat under the noise of the city.",
          "what's a word you've been thinking about lately?",
        ],
        replyOptions: [
          "hmmm. probably 'liminal'.",
          "supercalifragilisticexpialidocious.",
          "that's an unusual question.",
        ],
      },
      {
        beatKey: "slam-poet__reveal",
        suspectMessages: [
          "i think about words a lot. the shape of them.",
          "i get on stage and shout them at people sometimes.",
        ],
        replyOptions: [
          "that takes a lot of courage.",
          "you shout at them? for fun?",
          "you're a performer?",
        ],
      },
      {
        beatKey: "slam-poet__close",
        suspectMessages: [
          "it's not about courage. it just has to come out.",
          "you should come hear it for yourself sometime.",
        ],
        replyOptions: [
          "i'd be honored to.",
          "will you write a poem about me?",
          "where do you perform?",
        ],
      },
    ],
  },
  {
    id: "sourdough-baker",
    personaConcept: "A precise and patient sourdough baker who's up long before everyone else.",
    turns: [
      {
        beatKey: "sourdough-baker__open",
        suspectMessages: [
          "hey there. your profile seems warm and inviting.",
        ],
        replyOptions: [
          "thank you, that's kind.",
          "just like a fresh loaf of... something.",
          "what makes you say that?",
        ],
      },
      {
        beatKey: "sourdough-baker__warmup",
        suspectMessages: [
          "just a feeling. so, what's the best smell in the world?",
          "in your opinion.",
        ],
        replyOptions: [
          "freshly cut grass.",
          "gasoline. is that weird?",
          "i'll tell you mine if you tell me yours.",
        ],
      },
      {
        beatKey: "sourdough-baker__reveal",
        suspectMessages: [
          "for me, it's baking bread. first thing in the morning.",
          "my sourdough starter is older than most dogs.",
        ],
        replyOptions: [
          "that sounds amazing.",
          "you have a sourdough pet?",
          "you bake your own bread?",
        ],
      },
      {
        beatKey: "sourdough-baker__close",
        suspectMessages: [
          "every day. it's a whole process.",
          "i could bake you a loaf sometime if you'd like.",
        ],
        replyOptions: [
          "that's a very tempting offer.",
          "the way to my heart is through carbs.",
          "what kind do you make?",
        ],
      },
    ],
  },
  {
    id: "tattoo-apprentice",
    personaConcept: "A soft-spoken and observant tattoo apprentice with a love for quiet details.",
    turns: [
      {
        beatKey: "tattoo-apprentice__open",
        suspectMessages: [
          "hi. you have a really nice smile.",
        ],
        replyOptions: [
          "oh, thank you.",
          "it's one of my better features.",
          "and you have an eye for detail.",
        ],
      },
      {
        beatKey: "tattoo-apprentice__warmup",
        suspectMessages: [
          "i try to. it's part of the job.",
          "so what's a piece of art you really love?",
        ],
        replyOptions: [
          "anything by monet.",
          "the last meme i saved to my phone.",
          "what's your job?",
        ],
      },
      {
        beatKey: "tattoo-apprentice__reveal",
        suspectMessages: [
          "i'm learning how to be a tattoo artist.",
          "it's a lot of drawing. and watching. and being quiet.",
        ],
        replyOptions: [
          "that must be fascinating.",
          "so you get to draw on people all day?",
          "where are you learning?",
        ],
      },
      {
        beatKey: "tattoo-apprentice__close",
        suspectMessages: [
          "it's mostly practice pads for now. still learning.",
          "maybe you could come see the shop sometime.",
        ],
        replyOptions: [
          "i'd really like that.",
          "will you give me a free tattoo?",
          "are you working on anything now?",
        ],
      },
    ],
  },
  {
    id: "trivia-host",
    personaConcept: "A competitive and slightly showy trivia host who loves being right.",
    turns: [
      {
        beatKey: "trivia-host__open",
        suspectMessages: [
          "i have a feeling you know some weirdly specific facts.",
        ],
        replyOptions: [
          "i do know a few things.",
          "is that a challenge?",
          "what gave you that impression?",
        ],
      },
      {
        beatKey: "trivia-host__warmup",
        suspectMessages: [
          "let's call it a friendly wager.",
          "quick, what's your best category? history, science, pop culture?",
        ],
        replyOptions: [
          "definitely pop culture.",
          "i'm a jack of all trades, master of none.",
          "what's yours?",
        ],
      },
      {
        beatKey: "trivia-host__reveal",
        suspectMessages: [
          "i have to be good at everything.",
          "comes with the territory of hosting a trivia night.",
        ],
        replyOptions: [
          "oh, that sounds so fun.",
          "a professional know-it-all. i like it.",
          "where do you host?",
        ],
      },
      {
        beatKey: "trivia-host__close",
        suspectMessages: [
          "it has its moments. keeps me sharp.",
          "you should come play sometime. see if you can win.",
        ],
        replyOptions: [
          "i'd love to try.",
          "challenge accepted.",
          "do i get a prize if i win?",
        ],
      },
    ],
  },
  {
    id: "urban-beekeeper",
    personaConcept: "A quirky and passionate beekeeper who finds zen in the buzzing of her hives.",
    turns: [
      {
        beatKey: "urban-beekeeper__open",
        suspectMessages: [
          "hey. you seem like someone who isn't afraid of bees.",
        ],
        replyOptions: [
          "i like bees just fine.",
          "are you a bee?",
          "that's a strange opener.",
        ],
      },
      {
        beatKey: "urban-beekeeper__warmup",
        suspectMessages: [
          "ha, not a bee. just an admirer.",
          "so what's your favorite thing about summer?",
        ],
        replyOptions: [
          "the long, sunny days.",
          "that everything is alive.",
          "air conditioning.",
        ],
      },
      {
        beatKey: "urban-beekeeper__reveal",
        suspectMessages: [
          "for me it's watching my hives get busy.",
          "i keep a few on my rooftop. they're very peaceful.",
        ],
        replyOptions: [
          "you have rooftop bees? that's amazing.",
          "so you're the queen bee.",
          "is that allowed in the city?",
        ],
      },
      {
        beatKey: "urban-beekeeper__close",
        suspectMessages: [
          "it is. they're surprisingly good neighbors.",
          "i could show you them sometime. and the honey they make.",
        ],
        replyOptions: [
          "i would be honored to meet them.",
          "free honey? i'm there.",
          "do you ever get stung?",
        ],
      },
    ],
  },
  {
    id: "wedding-photog",
    personaConcept: "A candid wedding photographer who's jaded by clichés but still believes in real moments.",
    turns: [
      {
        beatKey: "wedding-photog__open",
        suspectMessages: [
          "your photos look very natural. not posed.",
        ],
        replyOptions: [
          "thanks, i hate posing for photos.",
          "are you saying i'm not photogenic?",
          "you have a photographer's eye.",
        ],
      },
      {
        beatKey: "wedding-photog__warmup",
        suspectMessages: [
          "posed photos are the worst. so stiff.",
          "what's a moment from your day you wish you had a picture of?",
        ],
        replyOptions: [
          "my cat sleeping in a sunbeam.",
          "the look on my friend's face when i told a joke.",
          "that's a really thoughtful question.",
        ],
      },
      {
        beatKey: "wedding-photog__reveal",
        suspectMessages: [
          "i think about those moments a lot.",
          "i'm a wedding photographer, but i only take candid shots.",
        ],
        replyOptions: [
          "that must be so rewarding.",
          "do you get tired of all the weddings?",
          "you must see some interesting things.",
        ],
      },
      {
        beatKey: "wedding-photog__close",
        suspectMessages: [
          "i get tired of the chicken dance. but the real moments are good.",
          "maybe we could go somewhere and take some non-wedding photos.",
        ],
        replyOptions: [
          "i'd really like that.",
          "will you make me look cool?",
          "where would we go?",
        ],
      },
    ],
  },
];

/** Stable lookup by id — null if the id isn't in the pool. */
export function getInnocentTreeById(id: string): InnocentTree | null {
  for (const t of INNOCENT_TREE_POOL) {
    if (t.id === id) return t;
  }
  return null;
}

/** All ids in pool order; useful for tests + check-out fallback. */
export const INNOCENT_TREE_IDS: readonly string[] = INNOCENT_TREE_POOL.map(
  (t) => t.id,
);
