/**
 * Static, Metro-bundlable map of pre-generated voice clips.
 *
 * REGENERATED BY: `pnpm --filter @workspace/catfish run voice:pregen`
 *
 * Why static `require()` instead of dynamic file lookup:
 *   Metro needs to see literal `require("./audio/foo.mp3")` strings at
 *   build time so it knows to copy the asset into the bundle. A
 *   dynamic `require(string)` would break web + native builds equally.
 *
 * Each entry maps a stable `<characterKey>_<beatKey>_<lineIndex>`
 * key to the bundled asset reference (a number on native, an object
 * on web — both shapes are accepted by expo-audio's `useAudioPlayer`).
 *
 * If a lookup misses, the runtime falls back to the live TTS proxy.
 */

// AUTO-GENERATED — do not hand-edit between these markers.
// audio-pregen-start
const AUDIO_MANIFEST_RAW = {} as const;
// audio-pregen-end

export const AUDIO_MANIFEST: Readonly<Record<string, number | object>> =
  AUDIO_MANIFEST_RAW;

/**
 * Look up a pre-generated clip by its stable key. Returns `undefined`
 * if no clip has been pre-generated for this character / beat / line —
 * callers should fall back to the live TTS proxy in that case.
 */
export function getAudioAsset(key: string): number | object | undefined {
  return (AUDIO_MANIFEST as Record<string, number | object>)[key];
}

/**
 * Stable key shared by the pre-gen script and the runtime player so
 * the two stay in lockstep. Passing the components instead of the
 * filename keeps the encoding rule in one place.
 */
export function audioKey(
  characterKey: string,
  beatKey: string,
  lineIndex: number,
): string {
  return `${characterKey}_${beatKey}_${lineIndex}`;
}
