/**
 * Static, Metro-bundlable map of pre-generated voice clips.
 *
 * REGENERATED BY: `pnpm --filter @workspace/catfish run voice:pregen`
 *
 * Why static `require()` instead of dynamic file lookup:
 *   Metro needs to see literal `require("./audio/foo.mp3")` strings at
 *   build time so it knows to copy the asset into the bundle. A
 *   dynamic `require(string)` would break web + native builds equally.
 *
 * Each entry maps a stable `<characterKey>_<beatKey>_<lineIndex>`
 * key to the bundled asset reference (a number on native, an object
 * on web — both shapes are accepted by expo-audio's `useAudioPlayer`).
 *
 * If a lookup misses, the runtime falls back to the live TTS proxy.
 */

// AUTO-GENERATED — do not hand-edit between these markers.
// audio-pregen-start
const AUDIO_MANIFEST_RAW = {
  "delphine_delphine_meet_0": require("./audio/delphine_delphine_meet_0.mp3"),
  "delphine_delphine_meet_1": require("./audio/delphine_delphine_meet_1.mp3"),
  "delphine_delphine_open_0": require("./audio/delphine_delphine_open_0.mp3"),
  "delphine_delphine_open_1": require("./audio/delphine_delphine_open_1.mp3"),
  "delphine_delphine_surprise_0": require("./audio/delphine_delphine_surprise_0.mp3"),
  "delphine_delphine_surprise_1": require("./audio/delphine_delphine_surprise_1.mp3"),
  "innocent_callum_innocent_close_0": require("./audio/innocent_callum_innocent_close_0.mp3"),
  "innocent_callum_innocent_close_1": require("./audio/innocent_callum_innocent_close_1.mp3"),
  "innocent_callum_innocent_open_0": require("./audio/innocent_callum_innocent_open_0.mp3"),
  "innocent_callum_innocent_open_1": require("./audio/innocent_callum_innocent_open_1.mp3"),
  "innocent_callum_innocent_probe_0": require("./audio/innocent_callum_innocent_probe_0.mp3"),
  "innocent_callum_innocent_probe_1": require("./audio/innocent_callum_innocent_probe_1.mp3"),
  "innocent_callum_innocent_weekend_0": require("./audio/innocent_callum_innocent_weekend_0.mp3"),
  "innocent_callum_innocent_weekend_1": require("./audio/innocent_callum_innocent_weekend_1.mp3"),
  "innocent_domi_innocent_close_0": require("./audio/innocent_domi_innocent_close_0.mp3"),
  "innocent_domi_innocent_close_1": require("./audio/innocent_domi_innocent_close_1.mp3"),
  "innocent_domi_innocent_open_0": require("./audio/innocent_domi_innocent_open_0.mp3"),
  "innocent_domi_innocent_open_1": require("./audio/innocent_domi_innocent_open_1.mp3"),
  "innocent_domi_innocent_probe_0": require("./audio/innocent_domi_innocent_probe_0.mp3"),
  "innocent_domi_innocent_probe_1": require("./audio/innocent_domi_innocent_probe_1.mp3"),
  "innocent_domi_innocent_weekend_0": require("./audio/innocent_domi_innocent_weekend_0.mp3"),
  "innocent_domi_innocent_weekend_1": require("./audio/innocent_domi_innocent_weekend_1.mp3"),
  "innocent_dorothy_innocent_close_0": require("./audio/innocent_dorothy_innocent_close_0.mp3"),
  "innocent_dorothy_innocent_close_1": require("./audio/innocent_dorothy_innocent_close_1.mp3"),
  "innocent_dorothy_innocent_open_0": require("./audio/innocent_dorothy_innocent_open_0.mp3"),
  "innocent_dorothy_innocent_open_1": require("./audio/innocent_dorothy_innocent_open_1.mp3"),
  "innocent_dorothy_innocent_probe_0": require("./audio/innocent_dorothy_innocent_probe_0.mp3"),
  "innocent_dorothy_innocent_probe_1": require("./audio/innocent_dorothy_innocent_probe_1.mp3"),
  "innocent_dorothy_innocent_weekend_0": require("./audio/innocent_dorothy_innocent_weekend_0.mp3"),
  "innocent_dorothy_innocent_weekend_1": require("./audio/innocent_dorothy_innocent_weekend_1.mp3"),
  "innocent_drew_innocent_close_0": require("./audio/innocent_drew_innocent_close_0.mp3"),
  "innocent_drew_innocent_close_1": require("./audio/innocent_drew_innocent_close_1.mp3"),
  "innocent_drew_innocent_open_0": require("./audio/innocent_drew_innocent_open_0.mp3"),
  "innocent_drew_innocent_open_1": require("./audio/innocent_drew_innocent_open_1.mp3"),
  "innocent_drew_innocent_probe_0": require("./audio/innocent_drew_innocent_probe_0.mp3"),
  "innocent_drew_innocent_probe_1": require("./audio/innocent_drew_innocent_probe_1.mp3"),
  "innocent_drew_innocent_weekend_0": require("./audio/innocent_drew_innocent_weekend_0.mp3"),
  "innocent_drew_innocent_weekend_1": require("./audio/innocent_drew_innocent_weekend_1.mp3"),
  "innocent_emily_innocent_close_0": require("./audio/innocent_emily_innocent_close_0.mp3"),
  "innocent_emily_innocent_close_1": require("./audio/innocent_emily_innocent_close_1.mp3"),
  "innocent_emily_innocent_open_0": require("./audio/innocent_emily_innocent_open_0.mp3"),
  "innocent_emily_innocent_open_1": require("./audio/innocent_emily_innocent_open_1.mp3"),
  "innocent_emily_innocent_probe_0": require("./audio/innocent_emily_innocent_probe_0.mp3"),
  "innocent_emily_innocent_probe_1": require("./audio/innocent_emily_innocent_probe_1.mp3"),
  "innocent_emily_innocent_weekend_0": require("./audio/innocent_emily_innocent_weekend_0.mp3"),
  "innocent_emily_innocent_weekend_1": require("./audio/innocent_emily_innocent_weekend_1.mp3"),
  "jules_jules_alone_after_0": require("./audio/jules_jules_alone_after_0.mp3"),
  "jules_jules_alone_after_1": require("./audio/jules_jules_alone_after_1.mp3"),
  "jules_jules_closing_0": require("./audio/jules_jules_closing_0.mp3"),
  "jules_jules_closing_1": require("./audio/jules_jules_closing_1.mp3"),
  "jules_jules_lantern_0": require("./audio/jules_jules_lantern_0.mp3"),
  "jules_jules_lantern_1": require("./audio/jules_jules_lantern_1.mp3"),
  "jules_jules_open_0": require("./audio/jules_jules_open_0.mp3"),
  "jules_jules_open_1": require("./audio/jules_jules_open_1.mp3"),
  "kai_kai_drink_0": require("./audio/kai_kai_drink_0.mp3"),
  "kai_kai_drink_1": require("./audio/kai_kai_drink_1.mp3"),
  "kai_kai_invite_0": require("./audio/kai_kai_invite_0.mp3"),
  "kai_kai_invite_1": require("./audio/kai_kai_invite_1.mp3"),
  "kai_kai_open_0": require("./audio/kai_kai_open_0.mp3"),
  "kai_kai_open_1": require("./audio/kai_kai_open_1.mp3"),
  "miles_miles_ardenne_0": require("./audio/miles_miles_ardenne_0.mp3"),
  "miles_miles_ardenne_1": require("./audio/miles_miles_ardenne_1.mp3"),
  "miles_miles_between_projects_0": require("./audio/miles_miles_between_projects_0.mp3"),
  "miles_miles_between_projects_1": require("./audio/miles_miles_between_projects_1.mp3"),
  "miles_miles_canal_0": require("./audio/miles_miles_canal_0.mp3"),
  "miles_miles_canal_1": require("./audio/miles_miles_canal_1.mp3"),
  "miles_miles_open_0": require("./audio/miles_miles_open_0.mp3"),
  "miles_miles_open_1": require("./audio/miles_miles_open_1.mp3"),
  "ren_ren_earlybird_0": require("./audio/ren_ren_earlybird_0.mp3"),
  "ren_ren_earlybird_1": require("./audio/ren_ren_earlybird_1.mp3"),
  "ren_ren_invite_0": require("./audio/ren_ren_invite_0.mp3"),
  "ren_ren_invite_1": require("./audio/ren_ren_invite_1.mp3"),
  "ren_ren_open_0": require("./audio/ren_ren_open_0.mp3"),
  "ren_ren_open_1": require("./audio/ren_ren_open_1.mp3"),
  "river_river_alibi_0": require("./audio/river_river_alibi_0.mp3"),
  "river_river_alibi_1": require("./audio/river_river_alibi_1.mp3"),
  "river_river_invite_0": require("./audio/river_river_invite_0.mp3"),
  "river_river_invite_1": require("./audio/river_river_invite_1.mp3"),
  "river_river_open_0": require("./audio/river_river_open_0.mp3"),
  "river_river_open_1": require("./audio/river_river_open_1.mp3"),
  "sam_sam_alibi_0": require("./audio/sam_sam_alibi_0.mp3"),
  "sam_sam_alibi_1": require("./audio/sam_sam_alibi_1.mp3"),
  "sam_sam_invite_0": require("./audio/sam_sam_invite_0.mp3"),
  "sam_sam_invite_1": require("./audio/sam_sam_invite_1.mp3"),
  "sam_sam_open_0": require("./audio/sam_sam_open_0.mp3"),
  "sam_sam_open_1": require("./audio/sam_sam_open_1.mp3"),
  "tessa_tessa_callback_0": require("./audio/tessa_tessa_callback_0.mp3"),
  "tessa_tessa_callback_1": require("./audio/tessa_tessa_callback_1.mp3"),
  "tessa_tessa_lateshift_0": require("./audio/tessa_tessa_lateshift_0.mp3"),
  "tessa_tessa_lateshift_1": require("./audio/tessa_tessa_lateshift_1.mp3"),
  "tessa_tessa_open_0": require("./audio/tessa_tessa_open_0.mp3"),
  "tessa_tessa_open_1": require("./audio/tessa_tessa_open_1.mp3"),
} as const;
// audio-pregen-end

export const AUDIO_MANIFEST: Readonly<Record<string, number | object>> =
  AUDIO_MANIFEST_RAW;

/**
 * Look up a pre-generated clip by its stable key. Returns `undefined`
 * if no clip has been pre-generated for this character / beat / line —
 * callers should fall back to the live TTS proxy in that case.
 */
export function getAudioAsset(key: string): number | object | undefined {
  return (AUDIO_MANIFEST as Record<string, number | object>)[key];
}

/**
 * Stable key shared by the pre-gen script and the runtime player so
 * the two stay in lockstep. Passing the components instead of the
 * filename keeps the encoding rule in one place.
 */
export function audioKey(
  characterKey: string,
  beatKey: string,
  lineIndex: number,
): string {
  return `${characterKey}_${beatKey}_${lineIndex}`;
}
